apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Chart.Name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
