name: backend
on: 
  push:
    paths:
      - 'services/backend-service/**'
      - '.github/workflows/backend.yml'
jobs:
  backend:
    runs-on: ubuntu-latest
    env:
      BACKEND_PATH: "services/backend-service"
      BACKEND_NAME: "backend-service"
      AWS_ECR_ACCOUNT_URL: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
    steps:

      - uses: actions/checkout@v4.1.6

      - name: Mvn Package
        run: |
          cd $BACKEND_PATH
          mvn package -DskipTests --settings .m2/settings.xml
      
      - name: Mvn Test
        run: |
          cd $BACKEND_PATH
          mvn test --settings .m2/settings.xml
        
      - name: Docker Build
        run: |
          cd $BACKEND_PATH
          docker build -t $BACKEND_NAME .
          
      - name: ECR Publish
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin $AWS_ECR_ACCOUNT_URL
          docker tag $BACKEND_NAME:latest $AWS_ECR_ACCOUNT_URL/$BACKEND_NAME:latest
          docker push $AWS_ECR_ACCOUNT_URL/$BACKEND_NAME:latest
