name: backend
on: 
  push:
    paths:
      - 'services/backend-service/**'
      - '.github/workflows/backend.yml'
jobs:
  backend:
    runs-on: ubuntu-latest
    env:
      BACKEND_PATH: "services/backend-service"
    steps:

      - uses: actions/checkout@v4.1.6

      - name: Mvn Package
        run: |
          cd $BACKEND_PATH
          mvn package -DskipTests --settings .m2/settings.xml
      
      - name: Mvn Test
        run: |
          cd $BACKEND_PATH
          mvn test --settings .m2/settings.xml
        
      - name: Docker Build
        run: |
          cd $BACKEND_PATH
          docker build -t backend-service .
          
      - name: ECR Publish
        uses: docker://ghcr.io/kciter/aws-ecr-action:latest # https://github.com/marketplace/actions/aws-ecr
        with:
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          region: ${{ secrets.AWS_REGION }}
          repo: backend-service
          tags: latest,${{ github.sha }}
