name: terraform
on: [push]
jobs:
  validate-dev:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3.1.1
        with:
          terraform_version: 1.8.3

      - name: Terraform fmt
        run:  |
          cd infrastructure/environments/dev
          terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        run:  |
          cd infrastructure/environments/dev
          terraform init

      - name: Terraform Validate
        run: |
          cd infrastructure/environments/dev
          terraform validate
