name: terraform
on: 
  push:
    paths:
      - 'infrastructure/**'
      - '.github/workflows/terraform.yml'
      - '.github/actions/terraform-command/**'
jobs:
  validate-dev:
    runs-on: ubuntu-latest
    env:
      TERRAFORM_PATH: "infrastructure/environments/dev"
    steps:

      - uses: actions/checkout@v4.1.6 # https://github.com/marketplace/actions/checkout

      - uses: hashicorp/setup-terraform@v3.1.1 # https://github.com/marketplace/actions/hashicorp-setup-terraform
        with:
          terraform_version: 1.8.3

      - name: Terraform fmt
        uses: ./.github/actions/terraform-command
        with:
          path: ${{env.TERRAFORM_PATH}}
          command: fmt -check
        continue-on-error: true

      - name: Terraform Init
        uses: ./.github/actions/terraform-command
        with:
          path: ${{env.TERRAFORM_PATH}}
          command: init

      - name: Terraform Validate
        uses: ./.github/actions/terraform-command
        with:
          path: ${{env.TERRAFORM_PATH}}
          command: validate
