name: terraform
on: [push]
jobs:
  validate-dev:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.8.3

      - name: Terraform Validate
        run: |
          cd infrastructure/environments/dev
          terraform validate
